default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Timeclock_development
  host: containers-us-west-92.railway.app
  port: 6446

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: railwayapp_production
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>

