default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres or your_user
  password: your_password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Timeclock_development

test:
  <<: *default
  database: Timeclock_test

  production:
		  <<: *default
		  url: <%= ENV["postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}"] %>
		  database: railway
		  username: postgres
		  password: <%= ENV["DJGAVcECZSK1lWEShAqK"] %>

